version: "3.8"

services:
  person-detection-api:
    build: .
    container_name: person-detection-api
    restart: unless-stopped
    ports:
      - "80:8000"
    volumes:
      - ./.env:/app/.env
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
